- hosts: all
  become: yes
  vars:
    docker_image_tar: "myapp.tar"

  tasks:
    - name: Copy Docker image tar to remote server
      copy:
        src: "{{ docker_image_tar }}"
        dest: "/home/vboxuser/mytmp/{{ docker_image_tar }}"

    - name: Load Docker image on remote server
      shell: docker load -i /tmp/{{ docker_image_tar }}

    - name: Stop old container if exists
      shell: docker stop myapp || true

    - name: Remove old container if exists
      shell: docker rm myapp || true

    - name: Run new container
      shell: docker run -d --name myapp -p 5000:5000 myapp

    - name: Remove temporary tar file
      file:
        path: "/home/vboxuser/mytmp/{{ docker_image_tar }}"
        state: absent
